### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by DeDuplicate** [TitanKodi/Plugintools#1]
no six module
ModuleNotFoundError: No module named 'six'
how can i fix it?

**Comment by TitanKodi** [comment]
You must add the Script.module.six dependency to your addon.xml

**Comment by TitanKodi** [comment]
https://github.com/TitanKodi/AddonCreator/blob/342fb35cfade32e99383b4cbb1aa9974729ff7e1/plugin.video.mimediacenter/addon.xml#L9 here you have an example

**Comment by DeDuplicate** [comment]
thanks for your quick answer I get the URL in the logs but it's not working now(streaming URL)

**Comment by TitanKodi** [comment]
Look if the url works and if the url tries to play
